### ISSUE TITLE
mention homebrew and dash?

### ISSUE THREAD

**Issue by adriaanm** [scala/make-release-notes#135]

**Comment by SethTisue** [comment]
@adriaanm what's dash?

**Comment by retronym** [comment]
https://kapeli.com/dash

**Comment by SethTisue** [comment]
cool!

but, I think https://github.com/scala/make-release-notes/blob/2.12.x/hand-written.md#obtaining-scala is probably long enough already, and it might be a bit weird to tout homebrew without saying what to do on Linux, except using a package manager on Linux is liable to get you some outdated junk... and actually @dwijnand is working on it but homebrew doesn't have 2.12.0 yet either... in general, our announcements go out before these resources get updated, not after. so I'm gonna close this

**Comment by dwijnand** [comment]
https://github.com/Homebrew/homebrew-core/pull/6545
