### ISSUE TITLE
Available Projects for Scala 2.12 vs Scaladex

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/make-release-notes#200]
Hi guys regarding: https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md#scala-2120-rc2

In the index we have 155 projects for 2.12:
https://index.scala-lang.org/search?q=targets%3Ascala_2.12&page=1&sort=stars

**Comment by lrytz** [comment]
can you filter by binary version `2.12.0-RC2` in the index?

**Comment by MasseGuillaume** [comment]
I can add this ;-). It should not be hard.

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex/issues/284

**Comment by SethTisue** [comment]
closing this once, since 284 exists
