### ISSUE TITLE
Catalysts on 2.13.0-M3

### ISSUE THREAD

**Issue by ghost** [scala/make-release-notes#271]
see https://index.scala-lang.org/typelevel/catalysts/catalysts/0.6?target=_2.13.0-M3

But the cats build fails - see https://github.com/typelevel/cats/pull/2203 

The PR adds the build as allowed to fail on Travis, with the hope we can get "most" of the changes in if we have to wait for next `M`release. Any thoughts on the issue, btw?

**Comment by SethTisue** [comment]
fixed by https://github.com/scala/make-release-notes/commit/b9fb9a85c084460180603bc2e67dc9029245a43d

I won't have time this week to look at typelevel/cats#2203 I'm afraid

**Comment by ghost** [comment]
Np, thanks for feedback and this or too :+1
