### ISSUE TITLE
Separate "Available Projects" pages 

### ISSUE THREAD

**Issue by dwijnand** [scala/make-release-notes#275]
Just skim-reading I didn't notice that halfway into https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md it switches from "Available Projects for Scala 2.13.0-M4" to "Available Projects for Scala 2.13.0-M3".

Should we split the pages? If so split into M3 and M4 pages, or just split the M3 part out of the general projects-2.13.md page? Or just dump the M3 content?

I can do the work.

**Comment by SethTisue** [comment]
I think we can dump the M3 content at this point (perhaps replacing it with a link to the final version that included the M3 info).
